//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentConsumerClientSoap.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStudent")]
    public interface IStudent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/AddStudent", ReplyAction="http://tempuri.org/IStudent/AddStudentResponse")]
        StudentWcfService.Student AddStudent(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/AddStudent", ReplyAction="http://tempuri.org/IStudent/AddStudentResponse")]
        System.Threading.Tasks.Task<StudentWcfService.Student> AddStudentAsync(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/FindStudent", ReplyAction="http://tempuri.org/IStudent/FindStudentResponse")]
        StudentWcfService.Student FindStudent(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/FindStudent", ReplyAction="http://tempuri.org/IStudent/FindStudentResponse")]
        System.Threading.Tasks.Task<StudentWcfService.Student> FindStudentAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetAll", ReplyAction="http://tempuri.org/IStudent/GetAllResponse")]
        StudentWcfService.Student[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetAll", ReplyAction="http://tempuri.org/IStudent/GetAllResponse")]
        System.Threading.Tasks.Task<StudentWcfService.Student[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/RemoveStudent", ReplyAction="http://tempuri.org/IStudent/RemoveStudentResponse")]
        void RemoveStudent(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/RemoveStudent", ReplyAction="http://tempuri.org/IStudent/RemoveStudentResponse")]
        System.Threading.Tasks.Task RemoveStudentAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentChannel : StudentConsumerClientSoap.ServiceReference1.IStudent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentClient : System.ServiceModel.ClientBase<StudentConsumerClientSoap.ServiceReference1.IStudent>, StudentConsumerClientSoap.ServiceReference1.IStudent {
        
        public StudentClient() {
        }
        
        public StudentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StudentWcfService.Student AddStudent(int id, string name) {
            return base.Channel.AddStudent(id, name);
        }
        
        public System.Threading.Tasks.Task<StudentWcfService.Student> AddStudentAsync(int id, string name) {
            return base.Channel.AddStudentAsync(id, name);
        }
        
        public StudentWcfService.Student FindStudent(string name) {
            return base.Channel.FindStudent(name);
        }
        
        public System.Threading.Tasks.Task<StudentWcfService.Student> FindStudentAsync(string name) {
            return base.Channel.FindStudentAsync(name);
        }
        
        public StudentWcfService.Student[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<StudentWcfService.Student[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void RemoveStudent(string name) {
            base.Channel.RemoveStudent(name);
        }
        
        public System.Threading.Tasks.Task RemoveStudentAsync(string name) {
            return base.Channel.RemoveStudentAsync(name);
        }
    }
}
